import angular from 'angular';
import 'Firebase';
import 'angularfire';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './components';
import './home';
import './services';
import './places';


// Create and bootstrap application
const requires = [
  'ui.router',
  'firebase',

  'templates',
  'app.layout',
  'app.components',
  'app.home',
  'app.services',
  'app.places'
];

firebase.initializeApp({
  apiKey: 'AIzaSyBmsVvx08Eo6YyNvE8eIPsb72RD_FV693g',
  authDomain: 'wheres-the-best.firebaseapp.com',
  databaseURL: 'https://wheres-the-best.firebaseio.com',
  storageBucket: 'wheres-the-best.appspot.com',
});

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
